name: Call API on New Repo
'on':
  push:
    paths:
      - '**/*.json'
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install requests
      - name: Extract JSON file path
        id: step_one
        run: >
         json_file_path=$(git diff --name-only ${{ github.sha }} | grep '.json') 
        env:
         INPUT_JSON_FILE_PATH: '${{steps.step_one.outputs.json_file_path}}'
      - name: Call Python script
        run: python call_api.py
