name: Call API on New Repo
'on':
  push:
    paths:
      - '**/*.json'
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install requests
      - name: Extract JSON file path
        run: >

          json_file_path=$(git show --name-only ${{ github.sha }} | grep
          '.json')

          echo "$json_file_path" >> "$action_state"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$action_state" # This will output 'yellow'
      - name: Call Python script
        run: python call_api.py
        env:
          INPUT_JSON_FILE_PATH: '${{ steps.outputs.json_file_path }}'
