name: call reusable workflow with python artifact with new branch

on:
 workflow_dispatch:
jobs:
  job1:
   uses: anandu-m-s/reusableWorkflow/.github/workflows/newReusableWithPythonRead.yaml@test-demo


