name: call reusable workflow and pass a file

on:
 workflow_dispatch:
jobs:
  job1:
   uses: anandu-m-s/reusableWorkflow/.github/workflows/reusablewithfileread.yaml@main
  job2:
   runs-on: ubuntu-latest
   needs: job1
   steps:
     - run: echo ${{needs.job1.outputs.fileread}}

