name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World hiii!"
      - name: access secrets
        run: |
         echo "secrets in caller repo is: ${{ secrets.API_KEY }}"
