name: New workflow test

on:
  workflow_dispatch:
jobs:
  testJob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action new
        id: step3
        uses: actions/checkout@v3
      - name: access secrets
        id: step1
        run: |
          echo "secrets in repo is:secret"
